/* easy :: typescript */
/*
    A generator function that yields the Fibonacci sequence.
    The Fibonacci sequence is generated by the recurrence relation Xn = Xn-1 + Xn-2.
    The sequence starts with 0 and 1, and each subsequent number is the sum of the
    previous two.
    - -                  - -
    Time  :: O(1) ::    56ms
    Space :: O(1) :: 51.77MB
*/
// Solution entrypoint :: - -                                                          - -

function* fibGenerator(): Generator<number, any, number>
{
    let curr = 0;
    let next = 1;

    while ( true )
    {
        yield curr;
        [ curr, next ] = [ next, curr + next ];
    }
}

//  End. :: - -                                                                        - -